site_name: Doggies as a Service (DaaS) API Documentation
site_url: http://127.0.0.1:8000/dogs/
site_description: API Documentation Example

repo_url: https://github.com/lorieide/daas-tutorial.git
repo_name: daas-tutorial
edit_uri: blob/master/docs

theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  analytics: {gtag: 'G-ABC123'}
  highlightjs: true
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  
plugins:
    - search

nav:
  - Home: readme.md
  - Get Started: get-started.md
  - Obtain Access Tokens: authentication.md  
  - Common Use Cases (endpoints):
    - Determine Document Storage: document-storage-options.md
    - Retrieve and Manage Documents: document-retrieve-manage.md
    - Retrieve and Manage Templates: document-templates-manage.md
  - Reference:
    - Data Structures: data-structures.md
    - API Reference: https://cdl-justice.dev.cdlcloud.co.uk/ 
    - Error Codes: error-codes.md
  - Change History: change-history.md



